pipeline {
    agent any
    tools { 'node:node' }

    stages('checkout') {
        stage {
            steps {
                git credentialsId: 'b2f40516-fe7e-4d00-b5c7-a40cf058cc2c', url: 'https://github.com/Saikumar2517/react-1.git'
            }
        }
    }
    stages('Install Dependencies') {
        stage {
            steps {
                sh 'npm i'
            }
        }
    }
    stages('Build') {
        stage {
            steps {
                sh 'npm run build'
            }
        }
    }
}
